# Generated by Django 5.0.2 on 2024-02-14 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_admin',
            name='admin_confirmpassword',
        ),
    ]
