# Generated by Django 5.0.2 on 2024-02-20 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0005_tbl_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depatment_id', models.CharField(max_length=50)),
                ('course_name', models.CharField(max_length=50)),
                ('course_duration', models.CharField(max_length=50)),
                ('course_semester', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=50)),
                ('emp_contact', models.CharField(max_length=50)),
                ('emp_email', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sem_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_syllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=50)),
                ('subject_id', models.CharField(max_length=50)),
                ('semester_id', models.CharField(max_length=50)),
            ],
        ),
    ]
