# Generated by Django 5.0.2 on 2024-02-20 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0007_tbl_place'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_place',
            old_name='Place_name',
            new_name='place_name',
        ),
    ]
