# Generated by Django 5.0.2 on 2024-02-20 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0008_rename_place_name_tbl_place_place_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_place',
            name='district_id',
        ),
        migrations.AddField(
            model_name='tbl_place',
            name='district',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='administrator.tbl_district'),
            preserve_default=False,
        ),
    ]
