# Generated by Django 5.0.2 on 2024-02-20 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0009_remove_tbl_place_district_id_tbl_place_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_employee',
            name='depatment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='administrator.tbl_department'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tbl_employee',
            name='designation',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='administrator.tbl_designation'),
            preserve_default=False,
        ),
    ]
