# Generated by Django 5.0.2 on 2024-02-20 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0011_tbl_employee_emp_salary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_employee',
            old_name='depatment',
            new_name='department',
        ),
    ]
