# Generated by Django 5.0.2 on 2024-02-20 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0012_rename_depatment_tbl_employee_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_course',
            old_name='course_duration',
            new_name='c_duration',
        ),
        migrations.RenameField(
            model_name='tbl_course',
            old_name='course_name',
            new_name='c_name',
        ),
        migrations.RenameField(
            model_name='tbl_course',
            old_name='course_semester',
            new_name='c_sem',
        ),
        migrations.RemoveField(
            model_name='tbl_course',
            name='depatment_id',
        ),
        migrations.AddField(
            model_name='tbl_course',
            name='department',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='administrator.tbl_department'),
            preserve_default=False,
        ),
    ]
