# Generated by Django 5.0.2 on 2024-02-21 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0013_rename_course_duration_tbl_course_c_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_syllabus',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='tbl_syllabus',
            name='semester_id',
        ),
        migrations.RemoveField(
            model_name='tbl_syllabus',
            name='subject_id',
        ),
        migrations.AddField(
            model_name='tbl_syllabus',
            name='course',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='administrator.tbl_course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tbl_syllabus',
            name='semester',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='administrator.tbl_semester'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tbl_syllabus',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='administrator.tbl_subject'),
            preserve_default=False,
        ),
    ]
