# Generated by Django 5.0.2 on 2024-02-27 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0014_remove_tbl_syllabus_course_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_place',
            old_name='place_name',
            new_name='subcat_name',
        ),
        migrations.RemoveField(
            model_name='tbl_place',
            name='district',
        ),
        migrations.AddField(
            model_name='tbl_place',
            name='category',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='administrator.tbl_category'),
            preserve_default=False,
        ),
    ]
