# Generated by Django 5.0.2 on 2024-02-27 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0017_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('product_disc', models.CharField(max_length=50)),
                ('product_price', models.CharField(max_length=50)),
                ('product_photo', models.FileField(upload_to='Assets/ProductPhoto/')),
                ('product_status', models.IntegerField(default='0')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.tbl_place')),
            ],
        ),
    ]
