# Generated by Django 5.0.2 on 2024-03-29 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0021_tbl_brand_tbl_color'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_product',
        ),
    ]
