# Generated by Django 5.0.2 on 2024-03-29 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrator', '0021_tbl_brand_tbl_color'),
        ('guest', '0009_tbl_center_tbl_shop'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('product_details', models.CharField(max_length=50)),
                ('product_rate', models.CharField(max_length=50)),
                ('product_photo', models.FileField(upload_to='Assets/ServicePhoto/')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.tbl_brand')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.tbl_color')),
                ('ram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.tbl_ram')),
                ('rom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.tbl_rom')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guest.tbl_shop')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.tbl_subcategory')),
            ],
        ),
    ]
