# Generated by Django 5.0.2 on 2024-03-29 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_product',
            name='product_photo',
            field=models.FileField(upload_to='Assets/ProductPhoto/'),
        ),
    ]
