# Generated by Django 5.0.2 on 2024-04-02 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0003_tbl_stock'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_stock',
        ),
    ]
