# Generated by Django 5.0.2 on 2024-04-16 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0005_tbl_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_product',
            name='ram',
        ),
        migrations.RemoveField(
            model_name='tbl_product',
            name='rom',
        ),
        migrations.AlterField(
            model_name='tbl_product',
            name='product_details',
            field=models.CharField(max_length=500),
        ),
    ]
