# Generated by Django 5.0.2 on 2024-04-25 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0006_remove_tbl_product_ram_remove_tbl_product_rom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_product',
            name='second_hand',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
