# Generated by Django 5.0.2 on 2024-02-29 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0009_tbl_playereleven'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_playereleven',
        ),
    ]
