# Generated by Django 5.0.2 on 2024-02-29 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0010_delete_tbl_playereleven'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_playereleven',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Test.tbl_player')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Test.tbl_matchshedule')),
            ],
        ),
    ]
