# Generated by Django 5.0.2 on 2024-03-19 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0005_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_user',
            name='user_address',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
