# Generated by Django 5.0.2 on 2024-03-19 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0006_tbl_user_user_address'),
        ('user', '0004_remove_tbl_complaint_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_user',
        ),
    ]
