# Generated by Django 5.0.2 on 2024-03-19 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0021_tbl_brand_tbl_color'),
        ('guest', '0008_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_center',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center_name', models.CharField(max_length=50)),
                ('center_address', models.CharField(max_length=50)),
                ('center_contact', models.CharField(max_length=50)),
                ('center_email', models.CharField(max_length=50)),
                ('center_password', models.CharField(max_length=50)),
                ('center_logo', models.FileField(upload_to='Assets/CenterLogo/')),
                ('center_proof', models.FileField(upload_to='Assets/Centerproof/')),
                ('center_status', models.IntegerField(default='0')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.tbl_place')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=50)),
                ('shop_address', models.CharField(max_length=50)),
                ('shop_contact', models.CharField(max_length=50)),
                ('shop_email', models.CharField(max_length=50)),
                ('shop_password', models.CharField(max_length=50)),
                ('shop_logo', models.FileField(upload_to='Assets/ShopLogo/')),
                ('shop_proof', models.FileField(upload_to='Assets/Shopproof/')),
                ('shop_status', models.IntegerField(default='0')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.tbl_place')),
            ],
        ),
    ]
