# Generated by Django 5.0.2 on 2024-04-22 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0009_tbl_center_tbl_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_center',
            name='center_address',
            field=models.CharField(max_length=500),
        ),
    ]
