# Generated by Django 5.0.2 on 2024-04-22 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0010_alter_tbl_center_center_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_shop',
            name='shop_address',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='tbl_user',
            name='user_address',
            field=models.CharField(max_length=500),
        ),
    ]
