# Generated by Django 5.0.2 on 2024-03-06 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_complaint',
            name='complaint_status',
            field=models.IntegerField(default='0'),
        ),
    ]
