# Generated by Django 5.0.2 on 2024-03-06 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_tbl_complaint_complaint_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_complaint',
            name='complaint_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tbl_complaint',
            name='complaint_replydate',
            field=models.DateField(null=True),
        ),
    ]
