# Generated by Django 5.0.2 on 2024-03-19 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_tbl_complaint_complaint_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_complaint',
            name='user',
        ),
    ]
