# Generated by Django 5.0.2 on 2024-03-19 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_tbl_complaint_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_complaint',
        ),
    ]
