# Generated by Django 5.0.2 on 2024-03-29 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceCenter', '0001_initial'),
        ('Shop', '0002_alter_tbl_product_product_photo'),
        ('guest', '0009_tbl_center_tbl_shop'),
        ('user', '0006_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_productbooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField(auto_now_add=True)),
                ('booking_detail', models.CharField(max_length=50)),
                ('booking_status', models.IntegerField(default='0')),
                ('booking_amount', models.CharField(max_length=50)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop.tbl_product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guest.tbl_user')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_servicebooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField(auto_now_add=True)),
                ('booking_detail', models.CharField(max_length=50)),
                ('booking_status', models.IntegerField(default='0')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ServiceCenter.tbl_service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guest.tbl_user')),
            ],
        ),
    ]
