# Generated by Django 5.0.2 on 2024-04-01 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0002_alter_tbl_product_product_photo'),
        ('user', '0007_tbl_productbooking_tbl_servicebooking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_productbooking',
            name='booking_amount',
        ),
        migrations.RemoveField(
            model_name='tbl_productbooking',
            name='booking_detail',
        ),
        migrations.RemoveField(
            model_name='tbl_productbooking',
            name='product',
        ),
        migrations.AddField(
            model_name='tbl_productbooking',
            name='price',
            field=models.CharField(default='0', max_length=40),
        ),
        migrations.CreateModel(
            name='tbl_cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_qty', models.CharField(max_length=500)),
                ('cart_status', models.IntegerField(default='0')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.tbl_productbooking')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop.tbl_product')),
            ],
        ),
    ]
