# Generated by Django 5.0.2 on 2024-04-09 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0005_tbl_stock'),
        ('guest', '0009_tbl_center_tbl_shop'),
        ('user', '0008_remove_tbl_productbooking_booking_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_date', models.DateField(auto_now_add=True)),
                ('review_detail', models.CharField(max_length=50)),
                ('review_count', models.CharField(max_length=50)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop.tbl_product')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guest.tbl_user')),
            ],
        ),
        migrations.DeleteModel(
            name='tbl_servicebooking',
        ),
    ]
