# Generated by Django 5.0.2 on 2024-04-18 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_tbl_servicebooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_cart',
            name='ship_status',
            field=models.IntegerField(default='0'),
        ),
    ]
