# Generated by Django 5.0.2 on 2024-04-24 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_tbl_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_servicebooking',
        ),
    ]
